# Generated by Django 4.2.25 on 2025-10-11 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.TextField(help_text='JSON-serialized 4x4 board array')),
                ('score', models.IntegerField(default=0, help_text='Current game score')),
                ('is_over', models.BooleanField(default=False, help_text='Whether the game is over')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this game state was last modified')),
                ('user', models.OneToOneField(help_text='The user who owns this game state', on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game State',
                'verbose_name_plural': 'Game States',
            },
        ),
    ]
